apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: azure_admin@postgre-mcs
  POSTGRES_PASSWORD: 12345678Long
  POSTGRES_URL: jdbc:postgresql://postgre-mcs.postgres.database.azure.com:5432/postgres?createDatabaseIfNotExist=true
