apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: myusername
  POSTGRES_PASSWORD: mypassword
  POSTGRES_URL: jdbc:postgresql://10.244.0.12:5432/postgres?createDatabaseIfNotExist=true
