apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: microsoft
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_URL: jdbc:postgresql://postgres:5432/microsoft?createDatabaseIfNotExist=true
