apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pvol
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres-pvol"
