apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvclaim
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: postgres-pvol
  storageClassName: standard
