version: '3.7'
services:
  db:
    image: mariadb:10.5.8
    container_name: mysql-identity
#    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: stock
      MYSQL_USER: root
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./volumes/identity:/tmp