version: '3.7'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'microsoft'
    ports:
      - "5432:5432"
    volumes:
      - "./volumes/dbdata:/var/lib/postgresql/data"