version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: "always"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./rabbitmq-management-data:/data"